build: enable C++23
The sdbusplus generated headers use std::to_underlying, which is C++23.
Building against them at C++20 fails:

    Logging/Entry/common.hpp:338:57: error: 'to_underlying' is not a
    member of 'std'

Tested: p10bmc builds mboxd against the sdbusplus 9e789850d3 sysroot,
which fails without this change.

Change-Id: I213fc67a397426d31b156d067b84f7fe3ce6b9b2
Signed-off-by: Vic Luo <vic_luo@jabil.com>